# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuZNKGNnR0X4_bjfzfggSGv-6m1IVzha
"""

import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader

class SequenceDataset(Dataset):
    """
    Custom Dataset for loading tokenized sequence data from CSV files.
    The files contain 20 token columns (token_01-token_20) and 20
    corresponding attention mask columns (mask_01-mask_20) [1-3].
    """
    def __init__(self, file_path):
        # Load the CSV file
        df = pd.read_csv(file_path)

        # Extract token sequences (token_01 to token_20)
        # Vocabulary mapping: PAD=0, A=1, B=2, C=3, D=4 [1-3]
        token_cols = [f'token_{i:02d}' for i in range(1, 21)]
        self.tokens = torch.tensor(df[token_cols].values, dtype=torch.long)

        # Extract attention masks (mask_01 to mask_20)
        # Masks indicate valid vs padding tokens (1 for valid, 0 for PAD) [1, 4]
        mask_cols = [f'mask_{i:02d}' for i in range(1, 21)]
        self.masks = torch.tensor(df[mask_cols].values, dtype=torch.float)

        # Extract binary labels (predicting if the first token recurs in the second half) [1, 5]
        self.labels = torch.tensor(df['label'].values, dtype=torch.float).unsqueeze(1)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.tokens[idx], self.masks[idx], self.labels[idx]

def get_dataloaders(train_path="train.csv", val_path="validation.csv",
                    test_path="test.csv", batch_size=32):
    """
    Creates DataLoaders for the training, validation, and test sets.
    """
    train_ds = SequenceDataset(train_path)
    val_ds = SequenceDataset(val_path)
    test_ds = SequenceDataset(test_path)

    # Shuffle only the training data to ensure diversity in batches [Previous Turn]
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False)

    return train_loader, val_loader, test_loader

if __name__ == "__main__":
    # Example validation of data loading [1-3]
    try:
        tr, vl, ts = get_dataloaders()
        tokens, masks, labels = next(iter(tr))
        print(f"Data loading successful.")
        print(f"Tokens Shape: {tokens.shape}") # Expected: [batch_size, 20]
        print(f"Labels Shape: {labels.shape}") # Expected: [batch_size, 1]
    except FileNotFoundError as e:
        print(f"Error: Dataset files not found. Ensure train.csv, validation.csv, and test.csv are in the directory.")