# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6bBYrs6VSaDuAHvlvy-vpTCtZdbV5lZ
"""

import torch
import torch.nn as nn
import math

class PositionalEncoding(nn.Module):
    """
    Implements fixed sinusoidal positional encoding to provide the model with
    information about the relative/absolute position of tokens [Sources].
    """
    def __init__(self, d_model, max_len=20):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe.unsqueeze(0))

    def forward(self, x):
        # x shape: [batch_size, seq_len, d_model]
        return x + self.pe[:, :x.size(1), :]

class MultiHeadSelfAttention(nn.Module):
    """
    Implements multi-head self-attention without using nn.MultiheadAttention [Sources].
    Includes scaled dot-product attention logic.
    """
    def __init__(self, d_model, num_heads):
        super().__init__()
        assert d_model % num_heads == 0, "d_model must be divisible by num_heads"

        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = d_model // num_heads

        self.q_linear = nn.Linear(d_model, d_model)
        self.k_linear = nn.Linear(d_model, d_model)
        self.v_linear = nn.Linear(d_model, d_model)
        self.out_proj = nn.Linear(d_model, d_model)

    def forward(self, x, mask=None):
        batch_size, seq_len, _ = x.size()

        # 1. Linear projections and split into heads
        q = self.q_linear(x).view(batch_size, seq_len, self.num_heads, self.d_k).transpose(1, 2)
        k = self.k_linear(x).view(batch_size, seq_len, self.num_heads, self.d_k).transpose(1, 2)
        v = self.v_linear(x).view(batch_size, seq_len, self.num_heads, self.d_k).transpose(1, 2)

        # 2. Scaled Dot-Product Attention
        scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.d_k)

        if mask is not None:
            # mask shape: [batch_size, seq_len] -> convert to [batch_size, 1, 1, seq_len]
            mask = mask.unsqueeze(1).unsqueeze(2)
            scores = scores.masked_fill(mask == 0, float('-inf'))

        attn_weights = torch.softmax(scores, dim=-1)
        context = torch.matmul(attn_weights, v)

        # 3. Concatenate heads and project back
        context = context.transpose(1, 2).contiguous().view(batch_size, seq_len, self.d_model)
        return self.out_proj(context)

class TransformerEncoderBlock(nn.Module):
    """
    A single Transformer Encoder block consisting of MHA and FFN [Sources].
    """
    def __init__(self, d_model, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = MultiHeadSelfAttention(d_model, num_heads)
        self.norm1 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout)

        self.ffn = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.ReLU(),
            nn.Linear(d_ff, d_model)
        )
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout2 = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        # Sub-layer 1: Attention + Residual + Norm
        attn_out = self.self_attn(x, mask)
        x = self.norm1(x + self.dropout1(attn_out))

        # Sub-layer 2: Feed Forward + Residual + Norm
        ffn_out = self.ffn(x)
        x = self.norm2(x + self.dropout2(ffn_out))
        return x

class TransformerClassifier(nn.Module):
    """
    Top-level model for synthetic sequence classification [Sources].
    """
    def __init__(self, vocab_size=5, d_model=64, num_heads=4, d_ff=128, num_layers=1, use_pe=True):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.use_pe = use_pe
        if use_pe:
            self.pos_encoding = PositionalEncoding(d_model)

        self.layers = nn.ModuleList([
            TransformerEncoderBlock(d_model, num_heads, d_ff) for _ in range(num_layers)
        ])

        self.classifier = nn.Linear(d_model, 1)

    def forward(self, x, mask):
        # x: [batch_size, seq_len]
        # mask: [batch_size, seq_len] (1 for valid, 0 for PAD)

        x = self.embedding(x)
        if self.use_pe:
            x = self.pos_encoding(x)

        for layer in self.layers:
            x = layer(x, mask)

        # Mean pooling over non-padding tokens [Sources]
        # mask.unsqueeze(-1) expands [B, 20] to [B, 20, 1]
        mask_expanded = mask.unsqueeze(-1).expand(x.size())
        sum_embeddings = torch.sum(x * mask_expanded, dim=1)
        num_valid_tokens = torch.clamp(mask_expanded.sum(dim=1), min=1e-9)
        pooled = sum_embeddings / num_valid_tokens

        # Binary prediction
        return torch.sigmoid(self.classifier(pooled))