# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkFIBE27se2vxcLkqFH_-mvStt_L-RZc
"""

import torch
import torch.nn as nn
import time
import pandas as pd
from utils import set_seed, load_transformer_data, calculate_accuracy
# Note: Ensure TransformerClassifier and its dependencies are imported
# or defined in the same script.

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    epoch_loss = 0
    epoch_acc = 0
    for tokens, masks, labels in loader:
        tokens, masks, labels = tokens.to(device), masks.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(tokens, masks)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()
        epoch_acc += calculate_accuracy(outputs, labels).item()
    return epoch_loss / len(loader), epoch_acc / len(loader)

def validate(model, loader, criterion, device):
    model.eval()
    val_loss = 0
    val_acc = 0
    with torch.no_grad():
        for tokens, masks, labels in loader:
            tokens, masks, labels = tokens.to(device), masks.to(device), labels.to(device)
            outputs = model(tokens, masks)
            val_loss += criterion(outputs, labels).item()
            val_acc += calculate_accuracy(outputs, labels).item()
    return val_loss / len(loader), val_acc / len(loader)

def run_experiment(config, train_loader, val_loader, test_loader):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    set_seed(42) # Assignment requirement for reproducibility [Sources]

    model = TransformerClassifier(
        vocab_size=5, # PAD, A, B, C, D [Sources]
        d_model=config['d_model'],
        num_heads=config['num_heads'],
        d_ff=config['d_ff'],
        num_layers=config['num_layers'],
        use_pe=config['use_pe']
    ).to(device)

    param_count = sum(p.numel() for p in model.parameters())
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.BCELoss()

    start_time = time.time()
    for epoch in range(15): # 10 to 20 epochs recommended [Sources]
        train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, criterion, device)
        val_loss, val_acc = validate(model, val_loader, criterion, device)
        # Optional: Print progress per epoch here

    train_time = time.time() - start_time
    _, test_acc = validate(model, test_loader, criterion, device)

    return {
        "Variant": config['name'],
        "Val Acc": round(val_acc, 4),
        "Test Acc": round(test_acc, 4),
        "Time (s)": round(train_time, 2),
        "Params": param_count
    }

if __name__ == "__main__":
    # Load datasets using our utils
    train_dl = load_transformer_data("train.csv", shuffle=True)
    val_dl = load_transformer_data("validation.csv", shuffle=False)
    test_dl = load_transformer_data("test.csv", shuffle=False)

    # Define the three required variants [Sources]
    experiments = [
        {"name": "With PE (4 Heads)", "use_pe": True, "num_heads": 4, "d_model": 64, "d_ff": 128, "num_layers": 1},
        {"name": "No PE (4 Heads)", "use_pe": False, "num_heads": 4, "d_model": 64, "d_ff": 128, "num_layers": 1},
        {"name": "With PE (1 Head)", "use_pe": True, "num_heads": 1, "d_model": 64, "d_ff": 128, "num_layers": 1}
    ]

    results = []
    for cfg in experiments:
        print(f"Running Experiment: {cfg['name']}...")
        res = run_experiment(cfg, train_dl, val_dl, test_dl)
        results.append(res)

    # Display Benchmark Table
    df = pd.DataFrame(results)
    print("\n--- Final Benchmark Results ---")
    print(df.to_string(index=False))