# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTXZ3jOnb1o2hNsKYBNzLCypWMILf-6k
"""

import pandas as pd
import torch
import numpy as np
import random
from torch.utils.data import DataLoader, TensorDataset

def set_seed(seed=42):
    """
    Sets random seeds for reproducibility as required by the assignment.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    # Ensure deterministic behavior in individual operations
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def load_transformer_data(file_path, batch_size=32, shuffle=True):
    """
    Loads data from the provided CSV files and returns a PyTorch DataLoader.

    The function extracts:
    - Tokens: columns token_01 through token_20 [Sources]
    - Masks: columns mask_01 through mask_20 [Sources]
    - Labels: the 'label' column [Sources]
    """
    df = pd.read_csv(file_path)

    # Extract token sequences (token_01 to token_20)
    # Using regex to capture all token columns in order
    token_cols = [f'token_{i:02d}' for i in range(1, 21)]
    tokens = torch.tensor(df[token_cols].values, dtype=torch.long)

    # Extract attention masks (mask_01 to mask_20)
    mask_cols = [f'mask_{i:02d}' for i in range(1, 21)]
    masks = torch.tensor(df[mask_cols].values, dtype=torch.float)

    # Extract binary labels
    labels = torch.tensor(df['label'].values, dtype=torch.float).unsqueeze(1)

    # Create Dataset and DataLoader
    dataset = TensorDataset(tokens, masks, labels)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

def calculate_accuracy(outputs, labels):
    """
    Helper to calculate accuracy for binary classification.
    """
    preds = (outputs > 0.5).float()
    correct = (preds == labels).float().sum()
    return correct / labels.size(0)